use anyhow::Result;
use std::fs;
use std::path::Path;

use crate::config::{ZeroConfig, PortValue};

pub fn generate(config: &ZeroConfig, output_dir: &Path) -> Result<()> {
    let mut compose = String::new();

    compose.push_str("# Generated by ZeroConfig\n");
    compose.push_str(&format!("# Project: {}\n\n",
        config.metadata.name.as_deref().unwrap_or("zeroconfig-project")));

    compose.push_str("version: '3.8'\n\n");
    compose.push_str("services:\n");

    // Add application service
    let app_name = config.metadata.name.as_deref().unwrap_or("app");
    compose.push_str(&format!("  {}:\n", app_name));
    compose.push_str("    build: .\n");
    compose.push_str("    ports:\n");
    compose.push_str("      - \"3000:3000\"\n");

    // Add environment variables
    if !config.env.is_empty() {
        compose.push_str("    environment:\n");
        for (key, value) in &config.env {
            if !value.contains("auto-generate") {
                compose.push_str(&format!("      {}: {}\n", key, value));
            } else {
                compose.push_str(&format!("      {}: ${{{}}}\n", key, key));
            }
        }
    }

    // Add depends_on for services
    if !config.services.is_empty() {
        compose.push_str("    depends_on:\n");
        for (service_name, _) in &config.services {
            compose.push_str(&format!("      - {}\n", service_name));
        }
    }

    compose.push_str("    networks:\n");
    compose.push_str("      - zeroconfig-network\n");
    compose.push_str("    restart: unless-stopped\n\n");

    // Add service containers
    for (service_name, service_config) in &config.services {
        compose.push_str(&format!("  {}:\n", service_name));

        // Determine image
        let image = match service_name.as_str() {
            "postgres" | "postgresql" => format!("postgres:{}", service_config.version),
            "redis" => format!("redis:{}", service_config.version),
            "mongodb" | "mongo" => format!("mongo:{}", service_config.version),
            "mysql" => format!("mysql:{}", service_config.version),
            "rabbitmq" => format!("rabbitmq:{}", service_config.version),
            "elasticsearch" => format!("elasticsearch:{}", service_config.version),
            "minio" => format!("minio/minio:{}", service_config.version),
            _ => format!("{}:{}", service_name, service_config.version),
        };

        compose.push_str(&format!("    image: {}\n", image));

        // Add ports
        let port = match &service_config.port {
            PortValue::Auto(_) => {
                match service_name.as_str() {
                    "postgres" | "postgresql" => "5432",
                    "redis" => "6379",
                    "mongodb" | "mongo" => "27017",
                    "mysql" => "3306",
                    "rabbitmq" => "5672",
                    "elasticsearch" => "9200",
                    "minio" => "9000",
                    _ => "8080",
                }
            },
            PortValue::Fixed(p) => {
                compose.push_str("    ports:\n");
                compose.push_str(&format!("      - \"{}:{}\"\n", p, p));
                continue;
            },
            PortValue::Range(_) => "8080",
        };

        compose.push_str("    ports:\n");
        compose.push_str(&format!("      - \"{}:{}\"\n", port, port));

        // Add environment variables for service
        if !service_config.environment.is_empty() {
            compose.push_str("    environment:\n");
            for (key, value) in &service_config.environment {
                compose.push_str(&format!("      {}: {}\n", key, value));
            }
        }

        // Add volumes
        if !service_config.volumes.is_empty() {
            compose.push_str("    volumes:\n");
            for volume in &service_config.volumes {
                compose.push_str(&format!("      - {}\n", volume));
            }
        }

        // Add custom command
        if let Some(cmd) = &service_config.command {
            compose.push_str(&format!("    command: {}\n", cmd));
        }

        compose.push_str("    networks:\n");
        compose.push_str("      - zeroconfig-network\n");
        compose.push_str("    restart: unless-stopped\n\n");
    }

    // Add networks section
    compose.push_str("networks:\n");
    compose.push_str("  zeroconfig-network:\n");
    compose.push_str("    driver: bridge\n");

    // Add volumes section if needed
    let has_volumes = config.services.values().any(|s| !s.volumes.is_empty());
    if has_volumes {
        compose.push_str("\nvolumes:\n");
        for (service_name, service_config) in &config.services {
            if !service_config.volumes.is_empty() {
                compose.push_str(&format!("  {}-data:\n", service_name));
            }
        }
    }

    let output_path = output_dir.join("docker-compose.yml");
    fs::write(&output_path, compose)?;

    println!("✅ Generated: {}", output_path.display());
    Ok(())
}
