use anyhow::Result;
use std::fs;
use std::path::Path;

use crate::config::ZeroConfig;

pub fn generate(config: &ZeroConfig, output_dir: &Path) -> Result<()> {
    let mut dockerfile = String::new();

    // Determine base image from primary language
    let (base_image, package_manager_install) = if config.languages.contains_key("node") {
        let version = config.languages.get("node").unwrap();
        (format!("FROM node:{}-alpine", version), "RUN npm install")
    } else if config.languages.contains_key("python") {
        let version = config.languages.get("python").unwrap();
        (format!("FROM python:{}-slim", version), "RUN pip install -r requirements.txt")
    } else if config.languages.contains_key("go") {
        let version = config.languages.get("go").unwrap();
        (format!("FROM golang:{}-alpine", version), "RUN go mod download")
    } else if config.languages.contains_key("rust") {
        ("FROM rust:latest".to_string(), "RUN cargo build --release")
    } else {
        ("FROM ubuntu:22.04".to_string(), "# No package manager install")
    };

    dockerfile.push_str(&format!("# Generated by ZeroConfig\n"));
    dockerfile.push_str(&format!("# Project: {}\n\n",
        config.metadata.name.as_deref().unwrap_or("zeroconfig-project")));

    dockerfile.push_str(&base_image);
    dockerfile.push_str("\n\n");

    // Set working directory
    dockerfile.push_str("WORKDIR /app\n\n");

    // Copy dependency files first (for layer caching)
    if config.languages.contains_key("node") {
        dockerfile.push_str("# Copy package files\n");
        dockerfile.push_str("COPY package*.json ./\n\n");
    } else if config.languages.contains_key("python") {
        dockerfile.push_str("# Copy requirements\n");
        dockerfile.push_str("COPY requirements.txt ./\n\n");
    } else if config.languages.contains_key("go") {
        dockerfile.push_str("# Copy go mod files\n");
        dockerfile.push_str("COPY go.mod go.sum ./\n\n");
    } else if config.languages.contains_key("rust") {
        dockerfile.push_str("# Copy Cargo files\n");
        dockerfile.push_str("COPY Cargo.toml Cargo.lock ./\n\n");
    }

    // Install dependencies
    dockerfile.push_str("# Install dependencies\n");
    dockerfile.push_str(&package_manager_install);
    dockerfile.push_str("\n\n");

    // Copy application code
    dockerfile.push_str("# Copy application code\n");
    dockerfile.push_str("COPY . .\n\n");

    // Add environment variables
    if !config.env.is_empty() {
        dockerfile.push_str("# Environment variables\n");
        for (key, value) in &config.env {
            if !value.contains("auto-generate") {
                dockerfile.push_str(&format!("ENV {}={}\n", key, value));
            }
        }
        dockerfile.push_str("\n");
    }

    // Expose ports
    dockerfile.push_str("# Expose ports\n");
    dockerfile.push_str("EXPOSE 3000\n\n");

    // Add startup command
    if let Some(startup) = config.startup.first() {
        dockerfile.push_str("# Startup command\n");
        dockerfile.push_str(&format!("CMD [\"{}\"]\n", startup));
    } else if config.languages.contains_key("node") {
        dockerfile.push_str("CMD [\"npm\", \"start\"]\n");
    } else if config.languages.contains_key("python") {
        dockerfile.push_str("CMD [\"python\", \"main.py\"]\n");
    } else if config.languages.contains_key("go") {
        dockerfile.push_str("CMD [\"./app\"]\n");
    } else if config.languages.contains_key("rust") {
        dockerfile.push_str("CMD [\"./target/release/app\"]\n");
    }

    let output_path = output_dir.join("Dockerfile");
    fs::write(&output_path, dockerfile)?;

    println!("✅ Generated: {}", output_path.display());
    Ok(())
}
