use anyhow::Result;
use std::fs;
use std::path::Path;

use crate::config::ZeroConfig;
use crate::secrets::SecretGenerator;

pub fn generate(config: &ZeroConfig, output_dir: &Path) -> Result<()> {
    let mut envfile = String::new();

    envfile.push_str("# Generated by ZeroConfig\n");
    envfile.push_str(&format!("# Project: {}\n",
        config.metadata.name.as_deref().unwrap_or("zeroconfig-project")));
    envfile.push_str("# WARNING: This file contains secrets. Do not commit to version control!\n\n");

    // Add environment variables
    for (key, value) in &config.env {
        if value.contains("auto-generate") {
            // Generate appropriate secret based on key name
            let generated = auto_generate_secret(key);
            envfile.push_str(&format!("{}={}\n", key, generated));
        } else {
            envfile.push_str(&format!("{}={}\n", key, value));
        }
    }

    // Add service connection strings
    envfile.push_str("\n# Service Connection Strings\n");
    for (service_name, service_config) in &config.services {
        let connection_string = generate_connection_string(service_name, service_config);
        if let Some(conn_str) = connection_string {
            envfile.push_str(&format!("{}_URL={}\n", service_name.to_uppercase(), conn_str));
        }
    }

    let output_path = output_dir.join(".env");
    fs::write(&output_path, &envfile)?;

    let example_path = output_dir.join(".env.example");
    let example_content = envfile.replace(|c: char| c.is_alphanumeric() || c == '_', "X");
    fs::write(&example_path, example_content)?;

    println!("✅ Generated: {}", output_path.display());
    println!("✅ Generated: {}", example_path.display());
    Ok(())
}

fn auto_generate_secret(key: &str) -> String {
    let key_lower = key.to_lowercase();

    if key_lower.contains("jwt") || key_lower.contains("secret") {
        SecretGenerator::generate_jwt_secret()
    } else if key_lower.contains("api") && key_lower.contains("key") {
        SecretGenerator::generate_api_key()
    } else if key_lower.contains("password") || key_lower.contains("pass") {
        SecretGenerator::generate_db_password()
    } else {
        SecretGenerator::generate_alphanumeric(32)
    }
}

fn generate_connection_string(service_name: &str, _config: &crate::config::ServiceConfig) -> Option<String> {
    match service_name {
        "postgres" | "postgresql" => {
            Some(format!("postgresql://user:password@localhost:5432/database"))
        },
        "redis" => {
            Some(format!("redis://localhost:6379"))
        },
        "mongodb" | "mongo" => {
            Some(format!("mongodb://localhost:27017/database"))
        },
        "mysql" => {
            Some(format!("mysql://user:password@localhost:3306/database"))
        },
        "rabbitmq" => {
            Some(format!("amqp://guest:guest@localhost:5672"))
        },
        _ => None,
    }
}
