use anyhow::Result;
use std::fs;
use std::path::Path;

use crate::config::ZeroConfig;

pub fn generate(config: &ZeroConfig, output_dir: &Path) -> Result<()> {
    let mut workflow = String::new();

    workflow.push_str("# Generated by ZeroConfig\n");
    workflow.push_str(&format!("# Project: {}\n\n",
        config.metadata.name.as_deref().unwrap_or("zeroconfig-project")));

    workflow.push_str("name: CI/CD Pipeline\n\n");

    workflow.push_str("on:\n");
    workflow.push_str("  push:\n");
    workflow.push_str("    branches: [ main, develop ]\n");
    workflow.push_str("  pull_request:\n");
    workflow.push_str("    branches: [ main ]\n\n");

    workflow.push_str("jobs:\n");
    workflow.push_str("  build:\n");
    workflow.push_str("    runs-on: ubuntu-latest\n\n");

    // Add service containers
    if !config.services.is_empty() {
        workflow.push_str("    services:\n");

        for (service_name, service_config) in &config.services {
            workflow.push_str(&format!("      {}:\n", service_name));

            let image = match service_name.as_str() {
                "postgres" | "postgresql" => format!("postgres:{}", service_config.version),
                "redis" => format!("redis:{}", service_config.version),
                "mongodb" | "mongo" => format!("mongo:{}", service_config.version),
                "mysql" => format!("mysql:{}", service_config.version),
                _ => continue,
            };

            workflow.push_str(&format!("        image: {}\n", image));

            if !service_config.environment.is_empty() {
                workflow.push_str("        env:\n");
                for (key, value) in &service_config.environment {
                    workflow.push_str(&format!("          {}: {}\n", key, value));
                }
            }

            workflow.push_str("        options: >-\n");
            workflow.push_str("          --health-cmd pg_isready\n");
            workflow.push_str("          --health-interval 10s\n");
            workflow.push_str("          --health-timeout 5s\n");
            workflow.push_str("          --health-retries 5\n");
        }

        workflow.push_str("\n");
    }

    workflow.push_str("    steps:\n");
    workflow.push_str("    - name: Checkout code\n");
    workflow.push_str("      uses: actions/checkout@v3\n\n");

    // Add language-specific setup
    if config.languages.contains_key("node") {
        let version = config.languages.get("node").unwrap();
        workflow.push_str("    - name: Setup Node.js\n");
        workflow.push_str("      uses: actions/setup-node@v3\n");
        workflow.push_str("      with:\n");
        workflow.push_str(&format!("        node-version: '{}'\n", version));
        workflow.push_str("        cache: 'npm'\n\n");

        workflow.push_str("    - name: Install dependencies\n");
        workflow.push_str("      run: npm ci\n\n");

        workflow.push_str("    - name: Run tests\n");
        workflow.push_str("      run: npm test\n\n");

        workflow.push_str("    - name: Build\n");
        workflow.push_str("      run: npm run build\n\n");
    }

    if config.languages.contains_key("python") {
        let version = config.languages.get("python").unwrap();
        workflow.push_str("    - name: Setup Python\n");
        workflow.push_str("      uses: actions/setup-python@v4\n");
        workflow.push_str("      with:\n");
        workflow.push_str(&format!("        python-version: '{}'\n", version));
        workflow.push_str("        cache: 'pip'\n\n");

        workflow.push_str("    - name: Install dependencies\n");
        workflow.push_str("      run: |\n");
        workflow.push_str("        python -m pip install --upgrade pip\n");
        workflow.push_str("        pip install -r requirements.txt\n\n");

        workflow.push_str("    - name: Run tests\n");
        workflow.push_str("      run: pytest\n\n");
    }

    if config.languages.contains_key("go") {
        let version = config.languages.get("go").unwrap();
        workflow.push_str("    - name: Setup Go\n");
        workflow.push_str("      uses: actions/setup-go@v4\n");
        workflow.push_str("      with:\n");
        workflow.push_str(&format!("        go-version: '{}'\n", version));
        workflow.push_str("        cache: true\n\n");

        workflow.push_str("    - name: Install dependencies\n");
        workflow.push_str("      run: go mod download\n\n");

        workflow.push_str("    - name: Run tests\n");
        workflow.push_str("      run: go test -v ./...\n\n");

        workflow.push_str("    - name: Build\n");
        workflow.push_str("      run: go build -v ./...\n\n");
    }

    if config.languages.contains_key("rust") {
        workflow.push_str("    - name: Setup Rust\n");
        workflow.push_str("      uses: actions-rs/toolchain@v1\n");
        workflow.push_str("      with:\n");
        workflow.push_str("        toolchain: stable\n");
        workflow.push_str("        override: true\n\n");

        workflow.push_str("    - name: Build\n");
        workflow.push_str("      run: cargo build --release --verbose\n\n");

        workflow.push_str("    - name: Run tests\n");
        workflow.push_str("      run: cargo test --verbose\n\n");
    }

    // Add Docker build step
    workflow.push_str("    - name: Build Docker image\n");
    workflow.push_str("      run: docker build -t ${{ github.repository }}:${{ github.sha }} .\n\n");

    // Add deployment step (commented out)
    workflow.push_str("    # - name: Deploy\n");
    workflow.push_str("    #   run: |\n");
    workflow.push_str("    #     # Add your deployment commands here\n");

    let workflows_dir = output_dir.join(".github").join("workflows");
    fs::create_dir_all(&workflows_dir)?;

    let output_path = workflows_dir.join("ci.yml");
    fs::write(&output_path, workflow)?;

    println!("✅ Generated: {}", output_path.display());
    Ok(())
}
